version: "3.8"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow/dockerfile
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow_db
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__SECRET_KEY: "your_secret_key_here"
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: weather_db
    AZURE_CONNECTION_STRING: ${AZURE_CONNECTION_STRING}
    CONTAINER_NAME: ${CONTAINER_NAME}
  volumes:
    - ./airflow:/opt/airflow/dags   
    - ./extract:/opt/airflow/extract
    - ./transform:/opt/airflow/transform
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - weather_network

services:

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: weather_db
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "weather_db"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - weather_network

  # Airflow Webserver 
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]  
      interval: 30s
      retries: 5
      start_period: 30s
    restart: always

  # Airflow Scheduler
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: always

  # Airflow Init
  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: on-failure


  # Streamlit 
  streamlit:
    build:
      context: .
      dockerfile: load/dockerfile
    ports:
      - "8501:8501"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: weather_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - weather_network

volumes:
  pg_data:

networks:
  weather_network:
    driver: bridge