FROM apache/airflow:2.8.1-python3.11

USER root
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

USER airflow
COPY airflow/requirements-airflow.txt .
RUN pip install --no-cache-dir -r requirements-airflow.txt