FROM python:3.11-slim
 
WORKDIR /app
 
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
 
COPY load/requirements-streamlit.txt .
RUN pip install --no-cache-dir -r requirements-streamlit.txt
 
COPY load/visualize.py .
 
EXPOSE 8501
 
CMD ["streamlit", "run", "visualize.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]